import React, { Component } from 'react';
import { OrderedMap } from 'immutable';
import register from "babel-core/register";
import polyfill from "babel-polyfill";

export default class SearchForm extends Component {

  static propTypes = {
    onUpdate: React.PropTypes.func.isRequired,
    onClear: React.PropTypes.func.isRequired,
    github: React.PropTypes.object.isRequired
  };

  state = {
    language: "JavaScript",
    location: "London",
    page: 1
  };

  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.bindScroll();
    this.nextPage();
  }

  bindScroll() {
    window.onscroll = (ev) => {
      if ((window.innerHeight + window.scrollY) >= document.body.offsetHeight) {
        this.nextPage();
      }
    };
  }

  async nextPage() {
    let response = await this.props.github.search(
      this.state.language,
      this.state.location,
      this.state.page
    );

    let developers = {};

    for (let person of response.body.items) {
      developers[person.login] = person;
    }

    this.props.onUpdate(developers);
    this.setState({ page: this.state.page + 1 });
  }

  handleLocationChange(e) {
    this.setState({ location: e.target.value });
  }

  handleLanguageChange(e) {
    this.setState({ language: e.target.value });
  }

  onSubmit(e) {
    e.preventDefault();
    this.setState({ page: 1 });
    this.props.onClear();
    this.nextPage();
  }

  render() {
    return (
      <form className="navbar-form navbar-left" onSubmit={::this.onSubmit}>
        <div className="form-group">
          <label htmlFor="language">Find</label>
          <select id="language" className="form-control" name="language" value={this.state.language} onChange={::this.handleLanguageChange}>
            <option value="">Any Language</option>
            { Object.keys(this.languages).map(group => {
              return (
                <optgroup key={group} label={group}>
                  {this.languages[group].map(language => {
                    return <option key={language}>{language}</option>
                  })}
                </optgroup>
              )
            })}
          </select>
          <label htmlFor="location">developers in</label>
          <input type="text" className="form-control" id="location" name="location" onChange={::this.handleLocationChange} value={this.state.location}/>
        </div>
        <button type="submit" className="btn btn-primary">Search</button>
      </form>
    );
  }

  languages = {
    "Popular": [
      "ActionScript",
      "C",
      "C#",
      "C++",
      "Clojure",
      "CoffeeScript",
      "CSS",
      "Go",
      "Haskell",
      "HTML",
      "Java",
      "JavaScript",
      "Lua",
      "Matlab",
      "Objective-C",
      "Perl",
      "PHP",
      "Python",
      "R",
      "Ruby",
      "Scala",
      "Shell",
      "Swift",
      "TeX",
      "VimL"
    ],
    "Other": [
      "ABAP",
      "Ada",
      "Agda",
      "AGS Script",
      "Alloy",
      "AMPL",
      "Ant Build System",
      "ANTLR",
      "ApacheConf",
      "Apex",
      "API Blueprint",
      "APL",
      "AppleScript",
      "Arc",
      "Arduino",
      "AsciiDoc",
      "ASP",
      "AspectJ",
      "Assembly",
      "ATS",
      "Augeas",
      "AutoHotkey",
      "AutoIt",
      "Awk",
      "Batchfile",
      "Befunge",
      "Bison",
      "BitBake",
      "BlitzBasic",
      "BlitzMax",
      "Bluespec",
      "Boo",
      "Brainfuck",
      "Brightscript",
      "Bro",
      "C-ObjDump",
      "C2hs Haskell",
      "Cap'n Proto",
      "CartoCSS",
      "Ceylon",
      "Chapel",
      "Charity",
      "ChucK",
      "Cirru",
      "Clarion",
      "Clean",
      "Click",
      "CLIPS",
      "CMake",
      "COBOL",
      "ColdFusion",
      "ColdFusion CFC",
      "Common Lisp",
      "Component Pascal",
      "Cool",
      "Coq",
      "Cpp-ObjDump",
      "Creole",
      "Crystal",
      "Cucumber",
      "Cuda",
      "Cycript",
      "Cython",
      "D",
      "D-ObjDump",
      "Darcs Patch",
      "Dart",
      "desktop",
      "Diff",
      "DIGITAL Command Language",
      "DM",
      "DNS Zone",
      "Dockerfile",
      "Dogescript",
      "DTrace",
      "Dylan",
      "E",
      "Eagle",
      "eC",
      "Ecere Projects",
      "ECL",
      "ECLiPSe",
      "edn",
      "Eiffel",
      "Elixir",
      "Elm",
      "Emacs Lisp",
      "EmberScript",
      "Erlang",
      "F#",
      "Factor",
      "Fancy",
      "Fantom",
      "Filterscript",
      "fish",
      "FLUX",
      "Formatted",
      "Forth",
      "FORTRAN",
      "FreeMarker",
      "Frege",
      "G-code",
      "Game Maker Language",
      "GAMS",
      "GAP",
      "GAS",
      "GDScript",
      "Genshi",
      "Gentoo Ebuild",
      "Gentoo Eclass",
      "Gettext Catalog",
      "GLSL",
      "Glyph",
      "Gnuplot",
      "Golo",
      "Gosu",
      "Grace",
      "Gradle",
      "Grammatical Framework",
      "Graph Modeling Language",
      "Graphviz (DOT)",
      "Groff",
      "Groovy",
      "Groovy Server Pages",
      "Hack",
      "Haml",
      "Handlebars",
      "Harbour",
      "Haxe",
      "HCL",
      "HTML+Django",
      "HTML+EEX",
      "HTML+ERB",
      "HTML+PHP",
      "HTTP",
      "Hy",
      "HyPhy",
      "IDL",
      "Idris",
      "IGOR Pro",
      "Inform 7",
      "INI",
      "Inno Setup",
      "Io",
      "Ioke",
      "IRC log",
      "Isabelle",
      "Isabelle ROOT",
      "J",
      "Jade",
      "Jasmin",
      "Java Server Pages",
      "JFlex",
      "JSON",
      "JSON5",
      "JSONiq",
      "JSONLD",
      "JSX",
      "Julia",
      "Jupyter Notebook",
      "KiCad",
      "Kit",
      "Kotlin",
      "KRL",
      "LabVIEW",
      "Lasso",
      "Latte",
      "Lean",
      "Less",
      "Lex",
      "LFE",
      "LilyPond",
      "Limbo",
      "Linker Script",
      "Linux Kernel Module",
      "Liquid",
      "Literate Agda",
      "Literate CoffeeScript",
      "Literate Haskell",
      "LiveScript",
      "LLVM",
      "Logos",
      "Logtalk",
      "LOLCODE",
      "LookML",
      "LoomScript",
      "LSL",
      "M",
      "Makefile",
      "Mako",
      "Markdown",
      "Mask",
      "Mathematica",
      "Maven POM",
      "Max",
      "MAXScript",
      "MediaWiki",
      "Mercury",
      "Metal",
      "MiniD",
      "Mirah",
      "Modelica",
      "Modula-2",
      "Module Management System",
      "Monkey",
      "Moocode",
      "MoonScript",
      "MTML",
      "MUF",
      "mupad",
      "Myghty",
      "NCL",
      "Nemerle",
      "nesC",
      "NetLinx",
      "NetLinx+ERB",
      "NetLogo",
      "NewLisp",
      "Nginx",
      "Nimrod",
      "Ninja",
      "Nit",
      "Nix",
      "NL",
      "NSIS",
      "Nu",
      "NumPy",
      "ObjDump",
      "Objective-C++",
      "Objective-J",
      "OCaml",
      "Omgrofl",
      "ooc",
      "Opa",
      "Opal",
      "OpenCL",
      "OpenEdge ABL",
      "OpenSCAD",
      "Org",
      "Ox",
      "Oxygene",
      "Oz",
      "Pan",
      "Papyrus",
      "Parrot",
      "Parrot Assembly",
      "Parrot Internal Representation",
      "Pascal",
      "PAWN",
      "Perl6",
      "Pickle",
      "PicoLisp",
      "PigLatin",
      "Pike",
      "PLpgSQL",
      "PLSQL",
      "Pod",
      "PogoScript",
      "Pony",
      "PostScript",
      "PowerShell",
      "Processing",
      "Prolog",
      "Propeller Spin",
      "Protocol Buffer",
      "Public Key",
      "Puppet",
      "Pure Data",
      "PureBasic",
      "PureScript",
      "Python traceback",
      "QMake",
      "QML",
      "Racket",
      "Ragel in Ruby Host",
      "RAML",
      "Raw token data",
      "RDoc",
      "REALbasic",
      "Rebol",
      "Red",
      "Redcode",
      "RenderScript",
      "reStructuredText",
      "RHTML",
      "RMarkdown",
      "RobotFramework",
      "Rouge",
      "Rust",
      "Sage",
      "SaltStack",
      "SAS",
      "Sass",
      "Scaml",
      "Scheme",
      "Scilab",
      "SCSS",
      "Self",
      "ShellSession",
      "Shen",
      "Slash",
      "Slim",
      "Smali",
      "Smalltalk",
      "Smarty",
      "SMT",
      "SourcePawn",
      "SPARQL",
      "SQF",
      "SQL",
      "SQLPL",
      "Squirrel",
      "Standard ML",
      "Stata",
      "STON",
      "Stylus",
      "SuperCollider",
      "SVG",
      "SystemVerilog",
      "Tcl",
      "Tcsh",
      "Tea",
      "Text",
      "Textile",
      "Thrift",
      "TOML",
      "Turing",
      "Turtle",
      "Twig",
      "TXL",
      "TypeScript",
      "Unified Parallel C",
      "Unity3D Asset",
      "UnrealScript",
      "UrWeb",
      "Vala",
      "VCL",
      "Verilog",
      "VHDL",
      "Visual Basic",
      "Volt",
      "Vue",
      "Web Ontology Language",
      "WebIDL",
      "wisp",
      "X10",
      "xBase",
      "XC",
      "XML",
      "Xojo",
      "XPages",
      "XProc",
      "XQuery",
      "XS",
      "XSLT",
      "Xtend",
      "Yacc",
      "YAML",
      "Zephir",
      "Zimpl"
    ]
  };

}
